steps:
- name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
  args: ['-f', 'docker-compose.yaml', 'up', '-d', '--build']

- name: 'gcr.io/$PROJECT_ID/go-test'
  args: ['go', 'test', '-cover', '/go/src/go-soma']

images: ['gcr.io/$PROJECT_ID/go-test']
